### ISSUE TITLE
Reallocate the javascript functions in static/js/checker.js

### ISSUE THREAD

**Issue by allenlee820202** [dsngroup/nexcom-project#30]
Some js functions in the static/js/checker.js are unrelated to each other. Reallocate them into different .js files by their functionality may enhance the maintainability.
Is there any advise? @tz70s

**Comment by tz70s** [comment]
Sure, and then we can name the js-files clearer, not just **checker** as a poor meaning.

**Comment by allenlee820202** [comment]
Commited in b459c07b18dc68c9a318c63d702d7af8eaf3a602

**Comment by tz70s** [comment]
IMHO, the file names are bad taste, I think we should keep track on this.

**Comment by tz70s** [comment]
1. **Handler** is not necessary.
2. **Tab** is mostly not necessary either.
